# Generated by Django 4.2.29 on 2026-03-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitn_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Analyzing'), ('planning', 'Planning'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='analyzing', max_length=20),
        ),
    ]
