# Generated by Django 4.2.29 on 2026-03-26 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digitn_api', '0002_remove_project_expires_at_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='assistant', max_length=10)),
                ('content', models.TextField()),
                ('event_type', models.CharField(choices=[('file_created', 'File Created'), ('file_updated', 'File Updated'), ('message', 'Message'), ('error', 'Error'), ('phase_change', 'Phase Change'), ('complete', 'Complete')], default='message', max_length=20)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phase', models.CharField(blank=True, choices=[('analyzing', 'Analyzing'), ('planning', 'Planning'), ('building', 'Building'), ('ready', 'Ready')], max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sequence_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_events', to='digitn_api.project')),
            ],
            options={
                'db_table': 'terminal_events',
                'ordering': ['sequence_number', 'created_at'],
                'indexes': [models.Index(fields=['project', 'sequence_number'], name='terminal_ev_project_0e3a8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('stack', models.CharField(blank=True, max_length=100, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_jobs', to='digitn_api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'build_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='build_jobs_status_13d749_idx'), models.Index(fields=['project', 'status'], name='build_jobs_project_85c8c0_idx')],
            },
        ),
    ]
