# Generated by Django 4.2.29 on 2026-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitn_api', '0003_terminalevent_buildjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='terminalevent',
            name='event_type',
            field=models.CharField(choices=[('file_created', 'File Created'), ('file_updated', 'File Updated'), ('message', 'Message'), ('error', 'Error'), ('phase', 'Phase'), ('phase_change', 'Phase Change'), ('plan_start', 'Plan Start'), ('plan_chunk', 'Plan Chunk'), ('plan_end', 'Plan End'), ('status', 'Status'), ('complete', 'Complete')], default='message', max_length=20),
        ),
    ]
