# Generated by Django 4.2.29 on 2026-03-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitn_api', '0004_alter_buildjob_status_alter_project_public_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderchatmessage',
            name='event_type',
            field=models.CharField(choices=[('file_created', 'File Created'), ('file_updated', 'File Updated'), ('message', 'Message'), ('error', 'Error'), ('phase', 'Phase'), ('phase_change', 'Phase Change'), ('plan_start', 'Plan Start'), ('plan_chunk', 'Plan Chunk'), ('plan_end', 'Plan End'), ('status', 'Status'), ('signature', 'Signature'), ('complete', 'Complete')], default='message', max_length=20),
        ),
        migrations.AlterField(
            model_name='terminalevent',
            name='event_type',
            field=models.CharField(choices=[('file_created', 'File Created'), ('file_updated', 'File Updated'), ('message', 'Message'), ('error', 'Error'), ('phase', 'Phase'), ('phase_change', 'Phase Change'), ('plan_start', 'Plan Start'), ('plan_chunk', 'Plan Chunk'), ('plan_end', 'Plan End'), ('status', 'Status'), ('signature', 'Signature'), ('complete', 'Complete')], default='message', max_length=20),
        ),
    ]
