# Generated by Django 4.2.29 on 2026-03-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitn_api', '0005_alter_builderchatmessage_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildjob',
            name='tier',
            field=models.CharField(default='free', max_length=10),
        ),
    ]
