# Generated by Django 4.2.29 on 2026-04-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitn_api', '0006_add_tier_to_buildjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_slide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='presentation_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_slides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('webapp', 'Web App'), ('ecommerce', 'E-commerce'), ('api', 'API'), ('presentation', 'Presentation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='terminalevent',
            name='event_type',
            field=models.CharField(choices=[('file_created', 'File Created'), ('file_updated', 'File Updated'), ('message', 'Message'), ('error', 'Error'), ('phase', 'Phase'), ('phase_change', 'Phase Change'), ('plan_start', 'Plan Start'), ('plan_chunk', 'Plan Chunk'), ('plan_end', 'Plan End'), ('status', 'Status'), ('signature', 'Signature'), ('complete', 'Complete'), ('slide_start', 'Slide Start'), ('slide_content', 'Slide Content'), ('slide_complete', 'Slide Complete'), ('palette', 'Palette')], default='message', max_length=20),
        ),
    ]
